# Generated by Django 4.2.6 on 2023-11-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_amount',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_details',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='transaction_type',
        ),
    ]
