# Generated by Django 4.2.6 on 2023-11-11 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_wallet_balance_remove_wallet_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
