version: "3.10"

services:
  postgres_container:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: 'shoecart'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'Asif@123'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    volumes:
      - .:/app
    container_name: shoecart_container
    ports:
      - 8000:8000
    image: app:shoecart
    command: bash -c "apt-get update && apt-get install -y postgresql-client && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

    environment:
      .env

volumes:
  postgres_data:
