# Generated by Django 4.2.6 on 2023-10-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0003_alter_product_discount_price_alter_product_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='side_image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='theme_image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_image', models.ImageField(upload_to='product_images/')),
                ('side_image_1', models.ImageField(upload_to='product_images/')),
                ('side_image_2', models.ImageField(upload_to='product_images/')),
                ('side_image_3', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_home.product')),
            ],
        ),
    ]
