# Generated by Django 4.2.6 on 2023-10-21 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0006_remove_product_discount_product_discount_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='side_image_1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='side_image_2',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='side_image_3',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='theme_image',
        ),
    ]
