# Generated by Django 4.2.6 on 2023-10-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0008_trashedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrashedProduct',
        ),
    ]
