# Generated by Django 4.2.6 on 2023-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0011_remove_product_discount_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sizevariant',
            old_name='discount_price',
            new_name='discount_percent',
        ),
        migrations.AlterField(
            model_name='sizevariant',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
