# Generated by Django 4.2.7 on 2023-11-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0012_rename_discount_price_sizevariant_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('file_input', models.ImageField(upload_to='banners/')),
                ('banner_type', models.CharField(choices=[('main_banner', 'Main Banner'), ('mini_banner_left', 'Mini Banner Left'), ('mini_banner_center', 'Mini Banner Center'), ('mini_banner_right', 'Mini Banner Right')], default='main_banner', max_length=20)),
            ],
        ),
    ]
