# Generated by Django 4.2.7 on 2023-11-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0013_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='file_input',
            field=models.ImageField(default='0', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='subtitle',
            field=models.CharField(blank=True, default='03', max_length=250),
        ),
    ]
