# Generated by Django 4.2.7 on 2023-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0014_alter_banner_file_input_alter_banner_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
