# Generated by Django 4.2.6 on 2023-10-21 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_of_join',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
