# Generated by Django 4.2.6 on 2023-11-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_remove_coupons_maximum_order_amount_the_discount_percenetage_applicable_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='description',
        ),
    ]
