# Generated by Django 4.2.6 on 2023-11-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_couponusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='quantity',
            new_name='limit',
        ),
    ]
