# Generated by Django 4.2.6 on 2023-11-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='address',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
