# Generated by Django 4.2.6 on 2023-11-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_price',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
