# Generated by Django 4.2.6 on 2023-11-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_variant_orders_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='total_amount',
        ),
    ]
