# Generated by Django 4.2.6 on 2023-11-09 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_orders_status_ordersitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Cancell request send', 'Cancell request send')], default='Order confirmed', max_length=20),
        ),
        migrations.CreateModel(
            name='CancelledOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_reason', models.TextField()),
                ('cancelled_date', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordersitem')),
            ],
        ),
    ]
