# Generated by Django 4.2.6 on 2023-11-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orders_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_purchase_amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
