# Generated by Django 4.2.7 on 2023-11-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='ordersitem',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
